#!/bin/bash
# Author: Shubham Singh
# Purpose: Work on tcp4 layer to provide host header based routing using ipv4 dns resolution
# Known issues: wont work on ipv6

LINES=''
VPC='10.0.0.0/16'
ALLOW_VPC="-A OUTPUT -d 172.28.0.0/8 -p tcp -j ACCEPT"
ALLOW_VPN="-A OUTPUT -d 10.0.0.0/8 -p tcp -j ACCEPT"
FINAL_O_LINE="-A OUTPUT -p tcp -j DROP"
for i in $(echo google.com yahoo.com);
do

    for _ip in $(dig +short "$i" A)
    do
        # LINES="$LINES"$'\n'"${_ip}"
        L="-A OUTPUT -p tcp -d ${_ip} -j ACCEPT"
        LINES+=$'\n'"$L"
        # LINES="$LINES -A OUTPUT -p tcp -d ${_ip} -j ACCEPT"$'\n
    done
done
LINES+=$'\n'"$ALLOW_VPC"
LINES+=$'\n'"$ALLOW_VPN"
LINES+=$'\n'"$FINAL_O_LINE"
cat << EOF > /tmp/iptables
# Generated by iptables-save v1.4.21 on Mon Sep 21 20:05:42 2020
*nat
:PREROUTING ACCEPT [1622770:100749302]
:INPUT ACCEPT [192429:14459188]
:OUTPUT ACCEPT [1461302:110668282]
:POSTROUTING ACCEPT [23257:1395744]
-A POSTROUTING -s $VPC -o eth0 -j MASQUERADE
COMMIT
# Completed on Mon Sep 21 20:05:42 2020
# Generated by iptables-save v1.4.21 on Mon Sep 21 20:05:42 2020
*filter
:INPUT ACCEPT [29:1556]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [21:2046]
$LINES
COMMIT
# Completed on Mon Sep 21 20:05:42 2020
EOF

iptables-restore <  /tmp/iptables
iptables-save
curl  --connect-timeout 2.37 "google.com" -I
curl  --connect-timeout 2.37 "https://www.digitalocean.com/community/tutorials/iptables-essentials-common-firewall-rules-and-commands" -k -I
sleep 300
iptables -F


